### PR TITLE
Monkey patch

### PR DESCRIPTION
**Pull request by ableeb**
I added collective.monkeypatcher as the patches did not seem to be present after I installed and wrote a custom password validator.

### CODE REVIEW

**Comment by jochumdev** [comment]
Rebased this pep8 + c.monkeypatcher branch on top of [deactivatable](https://github.com/collective/collective.pwexpiry/pull/3).

**Comment by frapell** [comment]
@ableeb @pcdummy Never noticed this PR :-/

Is this deprecated in favor of deactivatable?

**Comment by jochumdev** [comment]
Yes, please first merge deactivateable.

**Comment by frisi** [comment]
@frapell this PR is still perfectly valid. 

the plan is:
- merge pr2 (DONE) and pr3 (TODO)
- rebase pr1 on top of deactivateable (#3) (DONE)
- and merge this one (TODO)
- do another pr for the password_history (#4)

**Pull request merged**
